export const STATUS = {
  NONE: undefined,
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  BUSY: 'BUSY'
};

export const TIMEOUT_HIDE = 4000;

export const URLS = {
  EMAIL: '/email',
  CONFIG: {
    APP: '/config/app',
    AGENT_EMAIL: '/config/agent-email'
  }
};

export const AGENT_EMAIL_FILE_TYPE = {
  TIMESHEET: 'TIMESHEET',
  INVOICE: 'INVOICE'
};

export const NOTIFICATIONS_TYPES = {
  INVALID_APP_CONFIGURATION: 'INVALID_APP_CONFIGURATION',
  INVALID_AGENT_EMAIL_CONFIGURATION: 'INVALID_AGENT_EMAIL_CONFIGURATION',
  EMAIL_SENT_SUCCESS: 'EMAIL_SENT_SUCCESS',
  EMAIL_SENT_FAILED: 'EMAIL_SENT_FAILED'
};

export const NOTIFICATION_THEMES = {
  DANGER: 'DANGER',
  WARN: 'WARN',
  SUCCESS: 'SUCCESS'
};

export default {
  STATUS,
  TIMEOUT_HIDE,
  URLS,
  AGENT_EMAIL_FILE_TYPE,
  NOTIFICATIONS_TYPES
};
